### ISSUE TITLE
I implemented like the example of package, successfully connected but writeText() doesn't even work !

### ISSUE THREAD

**Issue by sailinhtut** [xiaozhizhong/flutter_simple_bluetooth_printer#3]

**Comment by xiaozhizhong** [comment]
Any error logs? The print commands in the example is ZPL for zebra printer

**Comment by sp280898** [comment]
I/flutter (31761): BTException{error: BTError.errorWithMessage, message: can't not found writable characteristic}

**Comment by xiaozhizhong** [comment]
Sorry for replying so late. During printing, a writable characteristic is required on the printer, but some printers might not have it. You can try switching to the v1.0.0-preview branch and specify the characteristicId when printing. I will release a new version soon.
